name: Deploy to VDS

on:
  push:
    branches:
      - main  # или master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy code to VDS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VDS_USER }}@${{ secrets.VDS_HOST }} << 'EOF'
            cd ~/apps/nik_studio

            # Обновляем репозиторий
            git pull origin main

            # Backend
            cd backend_laravel
            composer install --no-dev
            php artisan migrate --force

            # Frontend
            cd ../frontend_next
            npm install
            npm run build

            # Перезапускаем процессы
            pm2 restart frontend || pm2 start "npm run start" --name frontend
            sudo systemctl restart laravel-backend.service || echo "перезапуск Laravel настроен отдельно"
          EOF
